version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    networks:
      - monitoring
    ports:
      - '9090:9090'
    user: '0'
    volumes:
      - ./prometheus/conf:/etc/prometheus
      - ./prometheus/prometheus_data:/prometheus
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    networks:
      - monitoring
    ports:
      - '3000:3000'
    user: '0'
    volumes:
      #- grafana_data:/var/lib/grafana
      - ./grafana/grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
      
networks:
  monitoring:
    external: true

volumes:
  grafana_data:
    external: true

