global:
  scrape_interval: 15s
      
scrape_configs:   
  - job_name: 'docker_prometheus_container' 
    scrape_interval: 5s 
    static_configs: 
      - targets: ['localhost:9090']
        
  - job_name: 'docker-metrics' #For Docker container monitoring 
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.10.191:9323']
      
  - job_name: 'node_162' #Node_exporter Node
    scrape_interval: 5s 
    static_configs: 
      - targets: ['192.168.10.162:9100']
      
  - job_name: 'node_163' #Node_exporter Node
    scrape_interval: 5s 
    static_configs: 
      - targets: ['192.168.10.163:9100']
       
  - job_name: 'node_191' #Node_exporter Node
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.10.191:9100']
        
